apiVersion: cube-idp.dev/v1alpha1
kind: Cube
metadata: {name: "{{NAME}}"}
spec:
  cluster: {provider: kind}
  engine: {type: flux}
  gateway: {pack: {{PACK}}, host: cube-idp.localtest.me, port: {{PORT}},
            ref: "{{PACK_DIR}}"}
